// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as FlagIcon from "./FlagIcon.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_promise2 from "rescript/lib/es6/js_promise2.js";
import * as ReactSelect from "./ReactSelect.js";
import ReactSelect$1 from "react-select";

function make(props) {
  var children = Caml_option.some(React.createElement(React.Fragment, undefined, React.createElement(FlagIcon.make, {
                country: props.value
              }), props.label));
  var newrecord = Caml_obj.obj_dup(props);
  return React.createElement(ReactSelect.ReactSelectOption.make, (newrecord.children = Caml_option.some(children), newrecord));
}

var CustomOption = {
  make: make
};

function getValueFromOption(keyword, options) {
  var idx = 0;
  var $$break = false;
  var key = keyword !== undefined ? keyword : "";
  while(!$$break && idx < options.length && key !== "") {
    var currentOption = Belt_Array.get(options, idx);
    var isFound = currentOption !== undefined ? Caml_option.valFromOption(currentOption).value === key : false;
    if (isFound) {
      $$break = true;
    } else {
      idx = idx + 1 | 0;
    }
  };
  if ($$break) {
    return Belt_Array.get(options, idx);
  }
  
}

function CountrySelect(props) {
  var onChange = props.onChange;
  var country = props.country;
  var placeholder = country !== undefined ? country : "Search";
  var match = React.useState(function () {
        return [];
      });
  var setOptions = match[1];
  var options = match[0];
  React.useEffect((function () {
          Js_promise2.then(fetch("https://gist.githubusercontent.com/rusty-key/659db3f4566df459bd59c8a53dc9f71f/raw/4127f9550ef063121c564025f6d27dceeb279623/counties.json"), (function (val) {
                  return Js_promise2.then(val.json(), (function (val) {
                                Curry._1(setOptions, (function (param) {
                                        return val;
                                      }));
                                return Promise.resolve(undefined);
                              }));
                }));
        }), [setOptions]);
  return React.createElement("div", undefined, React.createElement(ReactSelect$1, {
                  className: props.className,
                  components: {
                    Option: make
                  },
                  onChange: (function (value) {
                      Curry._1(onChange, value.value);
                    }),
                  options: options,
                  placeholder: placeholder,
                  value: Caml_option.some(getValueFromOption(country, options))
                }));
}

var make$1 = CountrySelect;

export {
  CustomOption ,
  getValueFromOption ,
  make$1 as make,
}
/* react Not a pure module */
