// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import 'flag-icons/css/flag-icons.min.css'
;

function FlagIcon(props) {
  return React.createElement("span", {
              className: "fi fi-" + props.country + ""
            });
}

var make = FlagIcon;

export {
  make ,
}
/*  Not a pure module */
