// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as React from "react";
import * as Client from "react-dom/client";

import './index.css'
;

var rootElement = document.querySelector("#root");

if (!(rootElement == null)) {
  var root = Client.createRoot(rootElement);
  root.render(React.createElement(App.make, {}));
}

export {
  
}
/*  Not a pure module */
