// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactSelect from "react-select";

var optionComponent = ReactSelect.components.Option;

function make(props) {
  return React.createElement(React.Fragment, undefined, React.createElement(optionComponent, props));
}

var ReactSelectOption = {
  optionComponent: optionComponent,
  make: make
};

export {
  ReactSelectOption ,
}
/* optionComponent Not a pure module */
