// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactSelect from "react-select";

var optionComponent = ReactSelect.components.Option;

function make(props) {
  return React.createElement(React.Fragment, undefined, React.createElement(optionComponent, props));
}

var ReactSelectOption = {
  optionComponent: optionComponent,
  make: make
};

var controlComponent = ReactSelect.components.Control;

function make$1(props) {
  return React.createElement(React.Fragment, undefined, React.createElement(controlComponent, props));
}

var ReactSelectControl = {
  controlComponent: controlComponent,
  make: make$1
};

export {
  ReactSelectOption ,
  ReactSelectControl ,
}
/* optionComponent Not a pure module */
